format = """
$directory\
[](fg:bg_1 bg:bg_2)\
$git_branch\
$git_status\
$character\
"""

right_format = """
($cmd_duration)\
[](fg:bg_3 bg:None)\
(\
($jobs)\
)\
($time)\
"""

add_newline = false

command_timeout = 1000

# Set "foo" as custom color palette
palette = "theme"

# Define custom colors
[palettes.theme]
# Overwrite existing color
#bg_1 = "#154159"
#bg_2 = "#26688c"
#bg_3 = "#3385b5"
#fg_1 = "#FFFFFF"
#fg_dimmed = "#AAAAAA"
bg_1 = "#e4b700"
bg_2 = "#b18e00"
bg_3 = "#7f6600"
bg_e = "#c0392b"
bg_s = "#b18e00"
fg_1 = "#000000"
fg_2 = "#DEDEDE"

[docker_context]
format = "[$symbol$context]($style)"
disabled = false

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
[kubernetes.user_aliases]
"dev.local.cluster.k8s" = "dev"
"root/.*" = "root"

[fill]
symbol = " "

[character]
format = "$symbol "
success_symbol = "[](fg:bg_2 bg:bg_s)[](fg:bg_s bg:None)"
error_symbol = "[](fg:bg_2 bg:bg_e)[](fg:bg_e bg:None)"
disabled=false

[line_break]
disabled = false

[directory]
format = "[ $path ]($style)"
style = "bg:bg_1 fg:fg_1"

[cmd_duration]
show_milliseconds = true
show_notifications = false
min_time = 1_000
style = "bg:None fg:fg_2"
format = "[$duration]($style) "

[jobs]
format = "[$symbol$number ]($style)"
style = "bg:bg_3 fg:fg_2"
number_threshold = 2
symbol_threshold = 1

[time]
disabled = false
format = "[$time [UTC](fg:fg_2 bg:bg_3) ]($style)"
time_format = "%H:%M"
utc_time_offset = "0"
style = "bg:bg_3 fg:fg_2"

[git_branch]
format = '[ $symbol$branch ]($style)'
style = "bg:bg_2 fg:fg_1"
symbol = " "

[git_status]
format = '([[($all_status$ahead_behind)](bg:bg_2 fg:fg_1)]($style))'
style = "bg:bg_2 fg:fg_1"
deleted = "x"

[git_metrics]
disabled = false
added_style = "bg:bg_2 fg:fg_2"
deleted_style = "bg:bg_2 fg:fg_2"
format = "([+$added]($added_style))([-$deleted]($deleted_style))"

[username]
format = "[ $user ]($style)"
style_user = "bg:None fg:fg_2"
show_always = true

[hostname]
ssh_only = true
format = "[@$hostname ]($style)"
style = "bg:bg_1 fg:fg_1"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
disabled = false
symbol = "🐹"
style = "bg:bg_3 fg:fg_1"
format = '[$symbol ($version) ]($style)'

[nodejs]
disabled = true
symbol = ""
style = "bg:bg_3"
format = '[[ $symbol ($version) ](bg:bg_3)]($style)'

[rust]
disabled = true
symbol = ""
style = "bg:bg_3"
format = '[[ $symbol ($version) ](bg:bg_3)]($style)'
